### PR TITLE
Fix the example lean file's location of add_comm.

### PR DESCRIPTION
**Pull request by Julian**
I'm assuming the intention was for this file to run, not error, but if indeed this was intentional to demonstrate what happens when there's a problem, obviously let me know.

(For now this is part of fixing #16 )

### CODE REVIEW

**Comment by jasonrute** [comment]
I thought this used to run.  Maybe lean changed.  I think the intention was to use [the example here](https://leanprover-community.github.io/lean-web-editor/), but I doubt it matters too much.

**Comment by PatrickMassot** [comment]
Yes, it's meant to work and it did work. Let's merge that as soon as we get back to a globally working state (I don't remember exactly how this file was meant to be used so I don't fancy merging blindly).

**Comment by Julian** [comment]
Looks like that lean web example also uses `nat.add_comm`, guess it maybe was originally in the global namespace and was moved to `nat`?

**Comment by bryangingechen** [comment]
> Looks like that lean web example also uses `nat.add_comm`, guess it maybe was originally in the global namespace and was moved to `nat`?

That's correct. It happened when lots of algebra was moved from Lean 3.13.0c to mathlib.

**Comment by jasonrute** [comment]
I'm just going to merge this.  The file is for the trio server example.  The example still "work", but gives weird examples with this file broken.

**Pull request merged**
